# Generated by Django 5.0 on 2023-12-20 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashfy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('icon', models.CharField(max_length=255)),
                ('checked', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('icon', models.CharField(max_length=255)),
                ('expense', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.IntegerField()),
                ('timestamp', models.DateTimeField()),
                ('amount', models.IntegerField()),
                ('detail', models.TextField()),
                ('expense', models.BooleanField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cashfy.account')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cashfy.category')),
            ],
        ),
    ]
