# Generated by Django 5.0 on 2023-12-23 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashfy', '0004_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='selection',
            field=models.CharField(default=2, max_length=255),
            preserve_default=False,
        ),
    ]
